name: CodeQL Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language:
          - javascript
          # Add other languages if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: Build and analyze
        run: |
          codeql database create --language=${{ matrix.language }} --source-root . --output=db
          codeql database analyze --database=db --output=results

      - name: Upload results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results/codeql.sarif
